### ISSUE TITLE
maven-embedder needs maven on classpath in order to compile  <http://abcl.org/trac/ticket/418>

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#10]
Periodically I remember issue #9 and then maven-embedder.lisp needs to be recompiled when abcl-asdf is required.  Periodically I tear my hair out trying to figure out how to make an initial test run of abcl.jar how to know that.

What do you think of wrapping the first part (up until init is defined) and then calling init inside an eval-when?

Might be nice to add a build target that installs maven if mvn isn't on PATH.
```
@@ -41,6 +41,7 @@ Test:
 
 |#
 
+(eval-when (:compile-toplevel  :load-toplevel :execute)
 (defparameter *maven-verbose* t
   "Stream to send output from the Maven Aether subsystem to, or NIL to muffle output")
 

@@ -222,7 +224,10 @@ of the mvn executable with an explicit value."
     (error "Please obtain and install maven-3.0.3 or later locally from <http://maven.apache.org/download.html>, then set ABCL-ASDF:*MVN-LIBS-DIRECTORY* to the directory containing maven-core-3.*.jar et. al."))
   (unless (ensure-mvn-version)
     (error "We need maven-3.0.3 or later."))  (add-directory-jars-to-class-path *mvn-libs-directory* nil)
-    (setf *init* t))
+  (setf *init* t))
+
+(init))
+
 ```

**Comment by easye** [comment]
Closed as not present on master.  See <http://abcl.org/trac/ticket/418#comment:3>.
