### ISSUE TITLE
LOOP loops on most-positive-fixnum

### ISSUE THREAD

**Issue by phoe** [armedbear/abcl#106]
```
(declaim (optimize (safety 0)))

(lambda ()
  (loop for x of-type fixnum
        from (1- most-positive-fixnum) to most-positive-fixnum
        do (progn)
        finally (print x)))

(compile nil *)

(funcall *)
```

The above loops even though it is conforming ANSI CL.

Rationale, related to ANSI-TEST `LOOP.1.39` and `LOOP.1.40`: https://gist.github.com/phoe/335fecfdc195bddd47ab0928b0e62e52

**Comment by easye** [comment]
Noted, thanks!

**Comment by phoe** [comment]
The issue is widespread and affects SBCL, ECL, CCL, CLISP, Clasp among others. Maybe once the fix is made for one of the implementations then the others can benefit from it.

**Comment by easye** [comment]
> The issue is widespread and affects SBCL, ECL, CCL, CLISP, Clasp among others. Maybe once the fix is made for one of the implementations then the others can benefit from it.

LOOP is usually one of those parts of an implementation that one doesn't wish to touch if one doesn't have to.  I would suppose that @beach's implementation in SICL would be the cleanest.

**Comment by phoe** [comment]
After some discussion, the related ANSI-TESTs were annotated with :ANSI-SPEC-PROBLEM since the spec is not clear on the values of iteration variables or whether they are allowed to overstep their limit. This means that the `TYPE` proclamation there might not be valid.
https://gitlab.common-lisp.net/ansi-test/ansi-test/merge_requests/23
