### ISSUE TITLE
read with *read-suppress* t should return eof-value if eor-errorp is nil

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#123]
Cherry pick https://github.com/armedbear/abcl/commit/dbba85a710ecc1baaafda38e820cf7fce40b05e5

[CLHS](http://www.lispworks.com/documentation/HyperSpec/Body/v_rd_sup.htm) says:

If the value of *read-suppress* is true, read, read-preserving-whitespace, read-delimited-list, and read-from-string all return a primary value of nil when they complete successfully; however, they continue to parse the representation of an object in the normal way, in order to skip over the object, and **continue to indicate end of file in the normal way**.

Checked against behavior of SBCL and Allegro

**Comment by easye** [comment]
Merged with <https://github.com/armedbear/abcl/pull/125>
