### ISSUE TITLE
CFFI problems c.f. <https://abcl.org/trac/ticket/464>

### ISSUE THREAD

**Issue by easye** [armedbear/abcl#127]
Failing CI with segv <https://travis-ci.org/easye/abcl/jobs/618633882#L7886>

Context of segv failures in CI  <https://travis-ci.org/easye/abcl/jobs/618633882>

`rdfs:seeAlso` <https://abcl.org/trac/ticket/464> .

**Comment by avodonosov** [comment]
Can it be related to https://github.com/cl-plus-ssl/cl-plus-ssl/issues/72?

**Comment by easye** [comment]
> Can it be related to [cl-plus-ssl/cl-plus-ssl#72](https://github.com/cl-plus-ssl/cl-plus-ssl/issues/72)?

Yes, I think that is definitely what is causing the problem, as ABCL is definitely using the BIO routines.  

Thanks ever so much for pointing this out!

**Comment by avodonosov** [comment]
@easye, thank you.

Ruthless breaks of backward compatibility is the approach in OpenSSL project, it's difficult to keep up with the changes.

Patches for warnings are welcome :)

**Comment by easye** [comment]
Patch for cl+ssl submitted as <https://github.com/cl-plus-ssl/cl-plus-ssl/pull/97>

**Comment by easye** [comment]
Patch accepted in master cl-plus-ssl <​https://github.com/cl-plus-ssl/cl-plus-ssl/pull/98/files>.

Awaiting Quicklisp distribution, Ultralisp et.al

**Comment by easye** [comment]
@avodonosov I still owe you a patch for the warnings for anyone using the BIO codepath.  Cheers!

**Comment by easye** [comment]
openjdk14 changed behavior; need <https://github.com/armedbear/cl-plus-ssl/tree/easye/openjdk14>. TODO: submit another pull request to @avodonosov , but first I owe a patch to signal a condition when *any* implementation attempts to use the BIO codepath for openssl-1.1.1ff.  Can't be that hard, can it?

**Comment by avodonosov** [comment]
@easye , if you have any useful addition other than that patch, I will gladly merge it.

Also note, ABCL tests are failing in the https://github.com/armedbear/cl-plus-ssl/tree/easye/openjdk14.
