### ISSUE TITLE
A bug in code-char

### ISSUE THREAD

**Issue by anarchodin** [armedbear/abcl#146]
I'm looking into Unicode normalisation, and noticed a strange - and deeply incorrect - behaviour of `code-char` when given code-points outside the BMP. Instead of erroring out, as expected of a system based on UTF-16, it silently disregards the high bits and returns a BMP codepoint.

The error stems from the use of the `Character.isValidCodePoint(n)`. This method simply doesn't do what the code wants it to - and the documentation I can find seems to indicate it never did. It checks if the integer is between 0 and 0x10FFFF - that is, inside the range Unicode assigns codepoints. The appropriate check is `Character.isBmpCodePoint(n)` or, equivalently, `n > 0 && n < 0xFFFF`, as you're really checking if the code point will fit in a single `char`.

**Comment by easye** [comment]
That our Streams are deeply inconsistent on Unicode points beyond UTF-16 BMP is a known problem.  Our standard answer has been: use FLEXI-STREAMS if you really need such things until we fix the Java implementation of character streams (c.f. org.armedbear.lisp.StreamReader et.al. looking for lines comments like 
```
// ### BUG: Codepoint conversion
```
 ).

That code was written for Java 5, which glossed over the lacuna `java.lang.Character` doesn't always correspond to a Java primitive `char`.  

I think I know enough to fix this pretty fast, [as part of the ongoing work on JCOERCE (and the potential introduction of a JCAST where appropriate)][1].

[1]: https://mailman.common-lisp.net/pipermail/armedbear-devel/2020-February/004038.html

(look for all the "FIXME Unicode code point comments in Stream.java).

**Comment by anarchodin** [comment]
I can imagine there are weird points there; as I understand it Java itself has a bit of a rough time with UTF-16. I've actually solved the normalisation issue I was dealing with, by simply decoding UTF-16 and working with integer code points rather than Lisp characters. This issue doesn't get in the way of that, I just happened to notice it when reading hexadecimal strings from Unicode data files and seeing what happened when I tried to turn them into characters.

**Comment by easye** [comment]
> […] I just happened to notice it when reading hexadecimal strings from Unicode data files and seeing what happened when I tried to turn them into characters.

If you time to paste  a rudimentary test here that shows the problem it would give me a leg up on fixing this.

**Comment by anarchodin** [comment]
A line from one of those files:
>    101FD;PHAISTOS DISC SIGN COMBINING OBLIQUE STROKE;Mn;220;NSM;;;;;N;;;;;

I'm interested in the 220, and a couple fields that I don't think are filled anywhere above U+FFFF. Now, if I try and be cute about this - which works in a few implementations that use UTF-32 internally - and read the code point value at the start straight into a character, ABCL gives me a character just fine. But:

```lisp
(parse-integer "101FD") ; => 66045
(char-code (code-char *)) ; => 509
````

Not good if you're building a hash table with character keys, especially as U+01FD has different characteristics of interest. Now, I knew ahead of time that this wouldn't actually work, but it definitely shouldn't give me a _different_ character.

**Comment by anarchodin** [comment]
Heh. I probably should have started by reading the hyperspec carefully. `code-char` is indeed not supposed to error out. It says:

> If no such character exists and one cannot be created, nil is returned.

`char-code` on the other hand would promptly choke on that, and this is the behaviour that would be implemented by exchanging `Character.isValidCodePoint(n)` for a check that n is less than 65536.
