### ISSUE TITLE
bug in invoke-restart <http://abcl.org/trac/ticket/427#ticket>

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#17]
See the comment at 
https://github.com/sbcl/sbcl/blob/88fd8640e118ace44185a90baac095025acec3c5/src/code/target-error.lisp#L165

The issue is when invoke-restart is called with an actual restart with a test condition rather than a symbol. Currently invoke-restart calls (compute-restarts nil). So in the case where you've computed restarts (based on the condition) and then choose one of them, that restart can be considered inactive because the test function is run again with condition=nil instead of the condition that was signaled (and tested for).

**Comment by alanruttenberg** [comment]
http://abcl.org/trac/ticket/427#ticket

**Comment by easye** [comment]
Closed with <http://abcl.org/trac/changeset/14950> <https://github.com/armedbear/abcl/commit/f9a6e43d81cbc017225f5b1d962c89f99b73bab4>
