### ISSUE TITLE
Using ABCL with Slime

### ISSUE THREAD

**Issue by paladfn** [armedbear/abcl#187]
I am trying to use ABCL as an inferior-lisp with Slime. Right now I have
```
(load (expand-file-name "~/quicklisp/slime-helper.el"))
(setq inferior-lisp-program "java -jar ~/bin/abcl-bin-1.6.1/abcl.jar")
```
and inferior-lisp fails to launch with M-x slime.

**Comment by easye** [comment]
Something like

```elisp
(require 'slime-autoloads)
(setq slime-truncate-lines nil)
;; (slime-setup '(slime-repl slime-repl-ansi-color
;;                slime-asdf
;;                slime-fancy
;;                slime-banner
;;                slime-presentations))
(slime-setup '(slime-fancy
               slime-repl
               slime-repl-ansi-color
               slime-asdf
               slime-banner))
               
(global-set-key "\C-cs" 'slime-selector)
(setq slime-lisp-implementations
      `((abcl
         ("~/work/abcl/abcl"))
```

**Comment by paladfn** [comment]
> helm-M-x-execute-command: Searching for program: No such file or directory, java -jar /home/paladfn/bin/abcl-bin-1.6.1/abcl.jar

That's what I got when I used:
```

(slime-setup '(slime-fancy
               slime-banner))
              
(setq slime-lisp-implementations
      `((abcl
         ("java -jar /home/paladfn/bin/abcl-bin-1.6.1/abcl.jar"))))
```

**Comment by easye** [comment]
> > helm-M-x-execute-command: Searching for program: No such file or directory, java -jar /home/paladfn/bin/abcl-bin-1.6.1/abcl.jar
> 
> That's what I got when I used:
> 
> ```
> 
> (slime-setup '(slime-fancy
>                slime-banner))
>               
> (setq slime-lisp-implementations
>       `((abcl
>          ("java -jar /home/paladfn/bin/abcl-bin-1.6.1/abcl.jar"))))
> ```

Ah, I forgot that SLIME needs each arg delimited in double quotes.  

Please try 
```lisp
(slime-setup '(slime-fancy
               slime-banner))
              
(setq slime-lisp-implementations
      `((abcl
         ("java" "-jar" "/home/paladfn/bin/abcl-bin-1.6.1/abcl.jar"))))
```

**Comment by paladfn** [comment]
Okay, with the delimited version you posted, I get:

> 
Error: Unable to access jarfile ~/bin/abcl-bin-1.6.1/abcl.jar

**Comment by paladfn** [comment]
I got it working! It required the fullpath for some reason.
```

(slime-setup '(slime-fancy
               slime-banner))
              
(setq slime-lisp-implementations
      `((abcl
         ("java" "-jar" "/home/paladfn/bin/abcl-bin-1.6.1/abcl.jar"))))

```
