### ISSUE TITLE
Printing java objects sometimes leads to exceptions - we should protect ourselves <http://abcl.org/trac/ticket/428>

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#19]

**Comment by alanruttenberg** [comment]
http://abcl.org/trac/ticket/428

**Comment by easye** [comment]
Closed with <http://abcl.org/trac/changeset/14952>
<​https://github.com/armedbear/abcl/commit/1f47c7707bd73f4dc12f0af9e2cca60713df6ba7>
