### ISSUE TITLE
Unable to build for new openjdk from source tarball

### ISSUE THREAD

**Issue by MTCoster** [armedbear/abcl#215]
The source tarballs are missing the `ci` directory, so this step from the build instructions is not possible and the ant build ultimately fails:

```
bash ci/create-abcl-properties.bash openjdk14
```

Is the absence of the CI scripts in the source bundle intentional?

**Comment by easye** [comment]
> Is the absence of the CI scripts in the source bundle intentional?

No, it is inadvertent. 

I will endeavor to incorporate them in the upcoming abcl-1.7.0.

**Comment by MTCoster** [comment]
Thanks for the speedy response, much appreciated :)

**Comment by easye** [comment]
Merged into master as <https://github.com/armedbear/abcl/commit/4fe94ee8e9bc328b81106c7fe05420dc7cf7257b>
