### ISSUE TITLE
[ABCL-CONTRIB] abcl-asdf failed to resolve Maven artifact version that contains v character.

### ISSUE THREAD

**Issue by momozor** [armedbear/abcl#236]
### Environment
- GNU/Linux Manjaro
- ABCL 1.7.0
- Ran with `ros -Q run`

### Code
```lisp
(defsystem :java/org.eclipse.jetty.jetty-server
    :defsystem-depends-on (abcl-asdf)
    :components ((:mvn "org.eclipse.jetty/jetty-server" :version "9.4.30.v20200611")))
```

### Stacktrace
```
; Caught SIMPLE-WARNING:
; Invalid :version specifier "9.4.30.v20200611" for component "org.eclipse.jetty/jetty-server" in #<ASDF/SYSTEM:SYSTEM "java/org.eclipse.jetty.jetty-server"> from file #P"/home/momozor/.cache/common-lisp/abcl-1.7.0-fasl43-linux-x64/home/momozor/.roswell/local-projects/experiment902/src/main.abcl", using NIL instead
```

**Comment by easye** [comment]
Hmm, not sure why that warning is issued.  It may be that the parsing is going through the ASDF routines before it is passed to ABCL-ASDF.  ASDF itself is rather strict about parsing version strings from what I remember, being pretty strict about semantic versioning.  

1.  The form you have posted *does* seem to work in spite of the warning, as it downloads the artifact for me.

2.  If you move the version into the ```:mvn``` component like 
```
  :components ((:module "mvn"
                :components ((:mvn "org.eclipse.jetty/jetty-server/9.4.30.v20200611")))
```
it both works and doesn't emit the error.  

Does it not load for you at all in your case?  Or is this "just" a warning?

**Comment by momozor** [comment]
@easye Ah yes. You are correct, it does download and load the artifact despite the warning.

>   `lisp :components ((:module "mvn"
                :components ((:mvn "org.eclipse.jetty/jetty-server/9.4.30.v20200611")))`

Using quoted form above instead doesn't issue the warning anymore.

Sorry for the trouble.

Closing this issue due for wrongful usage of abcl-asdf.

Thanks for the help!
