### ISSUE TITLE
Macroexpansion error when compiling latest CLX

### ISSUE THREAD

**Issue by lokedhs** [armedbear/abcl#240]
Using CLX from git: https://github.com/sharplispers/clx.git, build 7b133e82e1033f51278d2e5138c16dd602b45dc4

When compiling `gcontext.lisp`, the following error occurs: `Wrong number of arguments for XLIB::HOLDING-LOCK`

The definition of `HOLDING-LOCK` that is used can be found here: https://github.com/sharplispers/clx/blob/master/dependent.lisp#L565

This implementation uses exactly the same arguments as all the other definitions, so it should compile. The error suggests there is a problem in ABCL.

Note that the implementation itself probably won't work because it doesn't implement proper locking, but it shouldn't result in a compile error.

**Comment by easye** [comment]
I think that the problem (well, "a" problem), is that the CLX code that ABCL uses for the `conditional-store` macro hasn't been updated to pass the two required arguments in `holding-lock`:

<https://github.com/armedbear/clx/blob/master/dependent.lisp#L813>
```
#-(or (and clasp threads) ecl sbcl)
(progn
  (defvar *conditional-store-lock*
    (make-process-lock "conditional store"))
  (defmacro conditional-store (place old-value new-value)
    `(holding-lock (*conditional-store-lock*)
       (if (eq ,place ,old-value)
           (prog1 t
             (setf ,place ,new-value))
           nil))))
```

If this is true, than CLX should fail to compile for other implementations that `(or (and clasp threads) ecl sbcl)` is true, like `ccl`?

**Comment by easye** [comment]
Not a problem in ABCL, but in CLX. 

A pull to fix CLX now exists as <https://github.com/sharplispers/clx/pull/171>
