### ISSUE TITLE
Release abcl-1.8.0

### ISSUE THREAD

**Issue by easye** [armedbear/abcl#263]
IN-PROGRESS

**Comment by chenrui333** [comment]
Looks only 1.8.0 pdf shows up in the release folder.
![image](https://user-images.githubusercontent.com/1580956/96259550-c5e63000-0f8b-11eb-943c-fa3651ea7eab.png)

**Comment by easye** [comment]
The release date is 20.10.2020, but you can build it yerself in the meantime.  

I'm still hoping to get `call-next-method` "unhiden" from macros before then, but otherwise, it is complete.

**Comment by easye** [comment]
Current showstopped:  trunk will not execute from zipped artifacts with whitespace in path.

**Comment by easye** [comment]
rc10 binaries seem to be working well under Windows <https://abcl.org/releases/1.8.0/>

**Comment by easye** [comment]
Final (?) release candidates with cryptographic signatures uploaded to https://abcl.org/releases/1.8.0/

**Comment by easye** [comment]
Released <https://abcl-dev.blogspot.com/2020/10/abcl-180.html>.  

Finishing touches of the release (Maven artifacts usw.) forthcoming shortly.
