### ISSUE TITLE
compile-file then load loses the type information for vectors

### ISSUE THREAD

**Issue by Slids** [armedbear/abcl#266]
Repro:
1. First make a file ~/lose-type.lisp:
```
(defparameter *byte-vector*
  ;; field name, default value, value set by tests
  #.(make-array '(3) :element-type '(unsigned-byte 8) :initial-contents '(52 49 54)))

(defun print-type () (type-of *byte-vector*))
```

2. Load ABCL
3. (compile-file "~/los-type.lisp")
4. (load "~/los-type.abcl")
5. (print-type)
 --- Gives: (SIMPLE-VECTOR 3)

Error: Should be a (simple-vector 3 '(unsigned-byte 8))

**Comment by easye** [comment]
You meant that it should be 

```
(SIMPLE-ARRAY (UNSIGNED-BYTE 8) (3))
```

but point taken.  

Interestingly, your test case fails under ECL, but passes under SBCL, CCL, clisp, and lwpro.

Fixing this is a bit tricky, as the top-level `defparameter` form gets "compiled" into the following form, which is actually `eval`d when loading the file:

```
(PROGN (SYSTEM:PUT '#1=*BYTE-VECTOR* '#2=SYSTEM::SOURCE (CONS (LIST :VARIABLE "/Users/evenson/work/abcl/lose-type.lisp" 
0) (GET '#1#  '#2#  #3=NIL))) (DEFPARAMETER #1#  #(52 49 54)))
```
