### ISSUE TITLE
LOOP doesn't destructure correctly when there are more variables than values

### ISSUE THREAD

**Issue by sjl** [armedbear/abcl#274]
[The spec says](http://www.lispworks.com/documentation/lw60/CLHS/Body/06_aag.htm) (emphasis mine):

> Destructuring allows binding of a set of variables to a corresponding set of values anywhere that a value can normally be bound to a single variable. During loop expansion, each variable in the variable list is matched with the values in the values list. **If there are more variables in the variable list than there are values in the values list, the remaining variables are given a value of nil.** If there are more values than variables listed, the extra values are discarded.

So something like this should work:

```
[SBCL] CL-USER> (loop :with (a b) = '(1) :for (c d) = '(2) :do (return (list a b c d)))
(1 NIL 2 NIL)
```

But ABCL breaks if you provide more variables than values:

```
Armed Bear Common Lisp 1.7.1 
Java 11.0.8 Ubuntu 
OpenJDK 64-Bit Server VM 
Low-level initialization completed in 0.169 seconds. 
Startup completed in 0.782 seconds. 
Loading /home/sjl/.abclrc completed in 8.229 seconds. 
Type ":help" for a list of available commands. 
 

[Armed Bear] CL-USER> (loop :with (a b) = '(1) :for (c d) = '(2) :do (return (list a b c d))) 
#<THREAD "interpreter" {34E6D0BC}>: Debugger invoked on condition of type PROGRAM-ERROR 
  Wrong number of arguments for NIL. 
Restarts: 
  0: TOP-LEVEL Return to top level. 
[1] > 
```

ECL had the same issue: https://gitlab.com/embeddable-common-lisp/ecl/-/issues/605

**Comment by easye** [comment]
c.f. <https://abcl.org/trac/ticket/471>
