### ISSUE TITLE
CALL-NEXT-METHOD "hidden" behind a macro seems to confuse method function generator

### ISSUE THREAD

**Issue by scymtym** [armedbear/abcl#301]
A method in which a `call-next-method` call is "hidden" behind a macro such as
```lisp
(defmacro foo ()
  '(call-next-method))
(defmethod bar ((x something))
  (foo))
```
seems to be expanded such that `call-next-method` is not bound in the method body, resulting in `The function CALL-NEXT-METHOD is undefined.` when called. I think this is because https://github.com/armedbear/abcl/blob/bca11a225a64466c785e291d5d01f19fc8c09ac3/src/org/armedbear/lisp/clos.lisp#L2764 looks at the method body before macroexpansion.

**Comment by easye** [comment]
Confirmed as a problem in my local testing.  

The "naieve" solution 
```lisp
(walk-form (macroexpand body))
```
unfortunately doesn't work, so I will need to dig deeper.

**Comment by easye** [comment]
```
<pjb> easye: the easy way is to avoid using walk-form, and to generate the                
      code with both call-next-method and next-method-p defined (flet) in all             
      cases.          
```

**Comment by easye** [comment]
Patched via <https://github.com/armedbear/abcl/commit/32f6328bc5652b9c71acbed5b1f8b3c7016a2c25> in the upcoming abcl-1.8.0

Not entirely sure this works in all cases, but it certainly helps in some.  

TODO revisit `fast-function` binding.  It seems quite underutilized at matching more than two argument functions.
