### ISSUE TITLE
Homebrew formulae should target/compile for as much downward compatibility as possible

### ISSUE THREAD

**Issue by mdbergmann** [armedbear/abcl#351]
Right now the 'brew' abcl install compiles against openjdk 14 or even 15.
So, it won't run on an installed Java 11.

Not sure if this is the right place here or who is the maintainer of the brew formular.
Anyone knows?

**Comment by easye** [comment]
@mdbergmann I don't know who maintains the Homebrew recipe, but its definitely not me.  I would be happy to coordinate with Homebrew to somehow follow the MacPorts <https://github.com/macports/macports-ports/blob/master/lang/abcl/Portfile> stuff that I maintain.  

I will try to figure out who to talk to.

**Comment by benhormann** [comment]
This [PR](https://github.com/Homebrew/homebrew-core/pull/60114/files) changed the dependency from java to openjdk. No mention of needing to target 14, just would have been the latest at that time.

@mdbergmann Open a PR changing [line 30](https://github.com/Homebrew/homebrew-core/blob/master/Formula/abcl.rb#L30) from 14 to 8. It will probably also need a [revision](https://docs.brew.sh/Formula-Cookbook#formulae-revisions) to trigger a rebuild (same as the above PR did).

Or, to install a local build:
```
sed -i '' 30s/14/8/ $(brew --repo)/Library/Taps/homebrew/homebrew-core/Formula/abcl.rb
brew install abcl --build-from-source
```

**Comment by mdbergmann** [comment]
Thanks, I will do that.
I think, since support for Java 8 was dropped by Oracle the target JRE should be 11.

**Comment by easye** [comment]
> I think, since support for Java 8 was dropped by Oracle the target JRE should be 11.

The official ABCL releases are currently done with openjdk8, as there as still quite a few people using this platform.  If Homebrew still has an option to install openjdk8 I would recommend targeting that for the most broad support.  

>Should there be a dependency on installing a separate JDK?
>I would think that most people already have a JDK installed, so I wouldn't want to have another one.

It depends on how rigorous Homebrew is about finding/using JDK releases that weren't installed by Homebrew.  Under MacPorts, I am able to specify the range of openjdks found and present on the system that will compile and run ABCL, falling back to installing openjdk11 if no suitable ones can be found.

**Comment by benhormann** [comment]
Well I figured 8 since it is still supported (till 2026!), so the [openjdk@8 formula](https://formulae.brew.sh/formula/openjdk@8) will be around for a while.

The formula has openjdk as a dependency, so it will be installed.

**Comment by mdbergmann** [comment]
I think that we have to differentiate between making it bytecode compatible with Java 8 and running it on Java 8.
So compiling to Java 8 should be done, so can run on a large range of Javas.
However, Java 8 is not supported by Oracle and I don't know if security fixes (TLS protocol, ciphers, etc.) are backported, or ported to Java 8 in openJDK.
If yes, ok. Install openJDK 8. If not I don't wanna run it on openJDK 8.
But I wouldn't know how to get this separation working in brew formula.

**Comment by benhormann** [comment]
@mdbergmann My understanding is that the compile target is the bytecode compatibility.

The homebrew dependency is separate (and doesn't specify a version number in this formula). That's why it installed even though you have openjdk@11. There is a chance that someone will try the same with openjdk@8...
Otherwise maybe consider setting a minimum version ([line 24](https://github.com/Homebrew/homebrew-core/blob/master/Formula/abcl.rb#L24))?

@easye The compiled Lisp programs will have a bytecode version independent of this decision, right?

**Comment by easye** [comment]
> @easye The compiled Lisp programs will have a bytecode version independent of this decision, right?

Correct.  The fasl for a given Lisp source unit will be a zip archive containing Java class that actually have a classfile corresponding `(major minor)` version `(49 0)` (pre Java 5?) but nothing outside of the code in the ABCL `cl:load` function "knows" anything about this.

**Comment by mdbergmann** [comment]
My PR on homebrew-core got merged.
So this ticket can be closed.

**Comment by easye** [comment]
@mdbergmann Hmm.  I can't verify this as <https://github.com/Homebrew/homebrew-core/blob/master/Formula/abcl.rb> still references openjdk14.   You got a PR URI you can paster here out of curiosity. 

I'll close this pull request, though, as you believe your needs are met.  Feel free to re-open if there are more problems.

**Comment by mdbergmann** [comment]
Right, it's not merged yet.
I just looked at this comment. Not sure what he is telling me.
https://github.com/Homebrew/homebrew-core/pull/64675

**Comment by mdbergmann** [comment]
There are two CI operations still in the queue.
