### ISSUE TITLE
SSL failure - error:20080078:BIO routines:bio_write_intern:uninitialized

### ISSUE THREAD

**Issue by spainisnotequal** [armedbear/abcl#360]
When I evaluate:
`(dex:get "http://lisp.org/") `

I get the following error:
```
#<THREAD "interpreter" {54B254B1}>: Debugger invoked on condition of type SSL-ERROR-SSL
  A failure in the SSL library occurred on handle #<com.sun.jna.Pointer native@0x7f7d76f9a9e0 {7376D001}> (return code: 1).
SSL error queue:
error:20080078:BIO routines:bio_write_intern:uninitialized

Restarts:
  0: RETRY-REQUEST Retry the same request.
  1: TOP-LEVEL     Return to top level.
[1] CL-USER(3): 1
```
I've also tried to evaluate:
` (drakma:http-request "http://lisp.org/")`

With the following result:
```
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  SIGSEGV (0xb) at pc=0x00007f3ee7729070, pid=4651, tid=4669
  #
  # JRE version: OpenJDK Runtime Environment (11.0.9.1+1) (build 11.0.9.1+1-post-Debian-1deb10u2)
  # Java VM: OpenJDK 64-Bit Server VM (11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
  # Problematic frame:
  # C  [libcrypto.so.1.1+0xbe070]  BIO_free+0x60
  #
  # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  #
  # An error report file with more information is saved as:
  # /home/spainisnotequal/hs_err_pid4651.log
  #
  # If you would like to submit a bug report, please visit:
  #   https://bugs.debian.org/openjdk-11
  # The crash happened outside the Java Virtual Machine in native code.
  # See problematic frame for where to report the bug.
  #
```
The mentioned log file is this:
[hs_err_pid4651.log](https://github.com/armedbear/abcl/files/5719662/hs_err_pid4651.log)

Some info about my environment:

- Armed Bear Common Lisp 1.8.0
- Java 11.0.9.1 Debian
- OpenJDK 64-Bit Server VM
- JNA 5.6.0
- Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 4 cores, 7G,
- Debian GNU/Linux 10 (buster)

**Comment by easye** [comment]
Possibly the connection is getting upgraded to TLS, and you are using an old version of CL+SSL somewhere?  

CL+SSL has neen fixed in Quicklisp for a while as detailed in <https://github.com/armedbear/abcl/issues/127>

What version of CL+SSL do you have loaded?

**Comment by spainisnotequal** [comment]
If I'm not wrong, version cl+ssl-20190813-git (not sure how to get the version of a library, but that's the name of its directory in the directory _quicklisp/dists/quicklisp/software/_).

**Comment by spainisnotequal** [comment]
I've uploaded all my libraries using `(ql:update-dist "quicklisp")` and now it works fine (both dexador and drakma libraries).

@easye, my apologies. I'm sorry for opening this issue and making you lose your time.

**Comment by easye** [comment]
@spainisnotequal No wasted effort at all:  I'm glad things work for now, and we've created a public trail that will undoubtedly help many more in the future.
