### ISSUE TITLE
slime-edit-definition broken for source code in jar files

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#411]
Boils down to 
```lisp
(ext:pathname-jar-p "jar:file:///Users/alanr/repos/abcl/dist/abcl-aio.jar!/contrib/jss/invoke.lisp")
```
returning nil

I thought the problem as in a change to the java code for that..

```java
          if (arg instanceof Pathname) {
            Pathname p = coerceToPathname(arg);
            return p.isJar() ? T : NIL;
          } else {
            return NIL;
          }
```
In the earlier version there wasn't the check that the argument was a pathname. Not sure what the logic of the new one is.  Check arg is a pathname then coerce it to a pathname?

In any case, getting rid of it didn't fix the problem, so It's something in coerceToPathname, which also had changes.

**Comment by alanruttenberg** [comment]
Could also be fixed with a change to slime's abcl.lisp

```patch
index 7145b664..6be00de9 100644
--- a/swank/abcl.lisp
+++ b/swank/abcl.lisp
@@ -1005,7 +1005,7 @@
       (when (atom what)
         (setq what (list what sym)))
       (list (definition-specifier what)
-            (if (ext:pathname-jar-p path2)
+            (if (ext:pathname-jar-p (pathname path2))
                 `(:location
                   (:zip ,@(split-string (subseq path2 (length "jar:file:")) "!/"))
                   ;; pos never seems right. Use function name.
```

**Comment by easye** [comment]
As I "designed" things (which admittedly is a bit loosey-goosey in its documentation/implementation)

```
(ext:pathname-jar-p "jar:file:///Users/alanr/repos/abcl/dist/abcl-aio.jar!/contrib/jss/invoke.lisp")
```

should definitely return `nil`, it its argument is a string not a pathname of any kind.  

```
(ext:pathname-jar-p #p"jar:file:///Users/alanr/repos/abcl/dist/abcl-aio.jar!/contrib/jss/invoke.lisp")
```

returns `t` as expected.

**Comment by easye** [comment]
Resolved by patching SLIME appropiately.

**Comment by stassats** [comment]
> should definitely return nil, it its argument is a string not a pathname of any kind.

This is unlike the standard pathname functions, which take pathname designators.

**Comment by easye** [comment]
> This is unlike the standard pathname functions, which take pathname designators.

True, but I would argue that the proper analogy for `ext:pathname-jar-p` would be `cl:pathnamep` which is a type predicate <http://www.lispworks.com/documentation/HyperSpec/Body/f_pnp.htm>.   

```
(pathnamep "/etc/passwd") 
```

should never return `t`, no matter whether there is a readable `/etc/passwd` present, right?

**Comment by stassats** [comment]
Is there a type pathname-jar?

**Comment by easye** [comment]
> Is there a type pathname-jar?

Sort-of:  the type is actually named jar-pathname.  I might have had a good reason for reversing the naming, but now I just chalk it up to bad case of dyslexia.

```
(pathname #p"jar:file:///Users/alanr/repos/abcl/dist/abcl-aio.jar!/contrib/jss/invoke.lisp")
#P"jar:file:///Users/alanr/repos/abcl/dist/abcl-aio.jar!/contrib/jss/invoke.lisp"
CL-USER> (type-of *)
JAR-PATHNAME
```

**Comment by alanruttenberg** [comment]
On Sun, Nov 7, 2021 at 8:32 AM Mark Evenson ***@***.***>
wrote:

> As I "designed" things (which admittedly is a bit loosey-goosey in its
> documentation/implementation)
>
> (ext:pathname-jar-p "jar:file:///Users/alanr/repos/abcl/dist/abcl-aio.jar!/contrib/jss/invoke.lisp")
>
> should definitely return nil, it its argument is a string not a pathname
> of any kind.
>
That's fine. The fix works. I noticed it because it was a change - it had
worked in 1.6.1 which is the version I was updating from.
