### ISSUE TITLE
SUBTYPEP failures on ABCL 1.8.0

### ISSUE THREAD

**Issue by phoe** [armedbear/abcl#433]
From https://gitlab.common-lisp.net/alexandria/alexandria/-/jobs/27735 (@phmarek)

```lisp
Test ALEXANDRIA-TESTS::TYPE=.2 failed
Form: (ALEXANDRIA:TYPE= (QUOTE LIST) (QUOTE (OR NULL CONS)))
Expected values: T
                 T
Actual values: NIL
               T.
Test ALEXANDRIA-TESTS::TYPE=.3 failed
Form: (ALEXANDRIA:TYPE= (QUOTE NULL) (QUOTE (AND SYMBOL LIST)))
Expected values: T
                 T
Actual values: NIL
               NIL.
```

In the Bear:
```lisp
CL-USER(3): (subtypep '(or null cons) 'list)
T
T
CL-USER(4): (subtypep 'list '(or null cons))
NIL
NIL
CL-USER(5): (subtypep 'null '(and symbol list))
T
T
CL-USER(6): (subtypep '(and symbol list) 'null)
NIL
NIL
```

**Comment by alejandrozf** [comment]
I'm not a 100% sure of this but I've been reading the standard for [subtypep](http://clhs.lisp.se/Body/f_subtpp.htm) and it seems that  this behaviour is allowed.

![image](https://user-images.githubusercontent.com/8377636/151679406-039e7177-cdda-4381-8931-5dc54dff23ff.png)

**Comment by phoe** [comment]
> `subtypep` is permitted to return the values false and false only when at least one argument involves one of these type specifiers: `and`, `eql`, the list form of `function`, `member`, `not,` `or`, `satisfies`, or `values`.

Hm. As un-useful as it is for the end user, that's correct, and therefore not strictly a conformance bug. Looks like the Alexandria tests might need to get corrected in that case?...

**Comment by alejandrozf** [comment]
Yes maybe they should change it.
And also, maybe add some conditional warning  inside the code of **alexandria:type=**  when any of these type identifiers are used in at least one of the parameters.

**Comment by phoe** [comment]
https://gitlab.common-lisp.net/alexandria/alexandria/-/issues/26 was created, let's see how this goes.
