### ISSUE TITLE
jnew-runtime-class instances: print errors

### ISSUE THREAD

**Issue by Uthar** [armedbear/abcl#470]
Hey

I was playing around with creating instances of ad-hoc classes in a repl, but I noticed that there is an error when trying to print them. To prove this, here is the example code:

```lisp
(defparameter *foo-list*
  (jnew
   (jnew-runtime-class
    "FooList"
    :superclass "java.util.AbstractList"
    :methods '(("get" "java.lang.Object" (:int)
                (lambda (this index)
                  "Foo"))
               ("size" :int ()
                (lambda (this)
                  15)))))) ;; => *foo-list*

(jcall "get" *foo-list* 0) ;; => "Foo"
(jcall "size" *foo-list*) ;; => 15
(jcall "subList" *foo-list* 5 10) ;; => #<java.util.AbstractList$SubList [Foo, Foo, Foo, Foo, Foo] {7DF1B0DF}>

*foo-list* ;; => Condition of type ERROR: Class not found: FooList

```
So `jnew-runtime-class` itself works properly, but the repl print step fails. Not sure what could be the cause 🤔

<hr>

_Versions used:_
```
CL-USER(2): (lisp-implementation-version)
"1.8.0"
"OpenJDK_64-Bit_Server_VM-Oracle_Corporation-17.0.1+12-nixos"
"amd64-Linux-5.10.81"
```

**Comment by Uthar** [comment]
Maybe here [Java.java](https://github.com/armedbear/abcl/blob/0631ea551523bb93c06263e772fbe849008e2f68/src/org/armedbear/lisp/Java.java#L1400)

**Comment by easye** [comment]
> Maybe here [Java.java](https://github.com/armedbear/abcl/blob/0631ea551523bb93c06263e772fbe849008e2f68/src/org/armedbear/lisp/Java.java#L1400)
 
 Yeah, that looks likely.  I don't remember at the moment where in the code we create (and therefore name) the synthetic runtime classes, but adding a branch in Java.java to find the correspondence seems to be the right way forward.  
 
If you are able to patch things before I manage to get them, that would be great.  Otherwise I will dig through this when I have the time. 

Thanks for the bug!

**Comment by Uthar** [comment]
Thanks for the response. Hmm, it looks like this can be fixed by passing a class instead of a keyword to `print-java-object-by-class`, which actually loops on classes internally anyway. I attached a patch here: #471. What do you think about such a fix?

**Comment by easye** [comment]
> Thanks for the response. Hmm, it looks like this can be fixed by passing a class instead of a keyword to `print-java-object-by-class`, which actually loops on classes internally anyway. I attached a patch here: #471. What do you think about such a fix?

The fix looks good from visual inspection:  nice that we can do something meaningful in Java and not Lisp.  

Not near a "real" keyboard at a moment, but I will have a look at the pull request in the next day.  Thanks!

**Comment by Uthar** [comment]
This also seems to fix something like this:

```
> (jstatic "ofString" "java.net.http.HttpResponse$BodyHandlers")
Class not found: java.net.http.HttpResponse$BodyHandlers$$Lambda$215/0x00000008050abac
```

Leaving this around for future explorers.

**Comment by alessiostalla** [comment]
I don't know the code path here but IMHO a class.forName call is
unnecessary since you already have an instance on which you can do
getClass().getName()
