### ISSUE TITLE
Was 1.9.0 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [armedbear/abcl#487]
When Homebrew [updated the 1.9.0 release 9 days ago](https://github.com/Homebrew/homebrew-core/commit/d4538270da13f1866b6695e16f1cdc523163c11c) it had the checksum `28b2b05216b57eddcf44fb23c18f2a382a3d8c1a7103fc150c2592200840b68a` but when I download it now it has `5c0a915e2b43f54eb12d09b20e45d3efe4d995ca63e7f0b91b57e193f85c1124`. 
The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do so we generally err on the side of caution and ask upstream what happened.

**Comment by easye** [comment]
abcl-1.9.0 is currently at rc-1 to fix some last minute issues.  There have
been no cryptographic signatures for the binaries in Homebrew or the source
used to build then

I hope to finish the release of abxl-1.9.0 over the next few days.

**Comment by SMillerDev** [comment]
Oh, homebrew would rather not ship pre-releases, is there any place to check if the release is a pre-release?

**Comment by easye** [comment]
The PGP signatures like <https://abcl.org/releases/1.9.0/abcl-bin-1.9.0.zip.asc> don't resolve.
