### ISSUE TITLE
Failure to compile with IRONCLAD-0.57 from Quicklisp

### ISSUE THREAD

**Issue by easye** [armedbear/abcl#493]
Another blocker: apparently [#abcl190rc3](https://twitter.com/hashtag/abcl190rc3?src=hashtag_click) fails to compile [#IRONCLAD](https://twitter.com/hashtag/IRONCLAD?src=hashtag_click) 0.57 out of Quicklisp:

#+begin_example
The variable IRONCLAD::+GROESTL-COLS-512+ is unbound.

SOURCE-FILE "ironclad/digest/groestl" "groestl"
#+end_example

**Comment by alejandrozf** [comment]
Hi Mark

I couldn't reproduce it.

I cloned the _ironclad_ repository (which points to 0.57 version) and loaded locally with ASDF and it worked for me with the latest ABCL commit (afa59bb35f4)

I attached the REPL output I got
[log-repl-493.txt](https://github.com/armedbear/abcl/files/8774585/log-repl-493.txt)
.

**Comment by easye** [comment]
> I couldn't reproduce it.

Indeed, my failure doesn't seem widespread.  

The failure with `ironclad` seems to be just occurring on Apple Silicon M1 (`"aarch64-Mac_OS_X-12.4`).

```
CL-USER> (lisp-implementation-version)                                                                                                                                                                                    
"1.9.0"                                                                                                                                                                                                                   
"OpenJDK_64-Bit_Server_VM-OpenJDK_Porters_Group-17.0.3+7"                                                                                                                                                                 
"aarch64-Mac_OS_X-12.4"   
```

but working on on `x86_64-Mac_OS_X-10.15.7` and `"amd64-FreeBSD-12.2-RELEASE-p1`.  


I also need to see if openjdk11 works where openjdk17 doesn't. 

Thanks for the data point!

**Comment by Jaso-N7** [comment]
Hi, First off, thank you for the hard work and effort that went (and continuously goes) into ABCL.

I would like to report that I also experience this problem as reported by @easye on GNU Guix. The issue persists whether I load from QL, from the guix package cl-ironclad (v0.57) or ASDF loading the cloned repo as @alejandrozf suggested.

This is the output before the break / restart
```
;  in (DEFUN GROESTL-TABLE) . . .)
;  Caught STYLE-WARNING:
;       Undefined variable +GROESTL-TABLE+ assumed special

; (DEFMACRO GROESTL-EXT_BYTE . . .)
; (DEFMACRO GROESTL-COLUMN . . .)
```
The error reported
```
The variable IRONCLAD::+GROESTL-COLS-512+ is unbound.
    [Condition of type UNBOUND-VARIABLE]
```


```
CL-USER> (lisp-implementation-version)
"1.9.0"
"OpenJDK_64-Bit_Server_VM-IcedTea-1.8.0_292-b10"
"amd64-Linux-5.18.18-gnu"
```

Though testing on Windows 10, ironclad loads without issues.

**Comment by easye** [comment]
* <2022-09-11 Sun>
** TODO Ironclad failure
Workaround: use interpreted form by expicitly visiting file in
interactive Emacs buffer then M-x slime-compile-defun (i.e. C-c C-c on
the offending form).

**Comment by easye** [comment]
Closing issue as ironclad-0.58 from Quicklisp 2023-02-15 compiles and passes its test suite without issue.

No specific work was done on this problem as far as I know.
