### ISSUE TITLE
Can't make jnew-runtime-class with primitive array argument types

### ISSUE THREAD

**Issue by Uthar** [armedbear/abcl#516]
Works:

```
(java:jnew-runtime-class
 "test"
 :methods '(("test" :void ("java.lang.Object") (lambda (this) this))))
```

Doesn't work - throws `java.lang.ClassFormatError: Class name is empty or contains illegal character in descriptor in class file test`
```
(java:jnew-runtime-class
 "test"
 :methods '(("test" :void ("[D") (lambda (this) this))))
```

**Comment by Uthar** [comment]
The issue may stem from an invalid descriptor in method in the generated class file:

From working class:
```
 public Test(byte[]);
    descriptor: ([B)V
```

From class created by the not working example code above:
```
public void test2([D);
    descriptor: (L[D;)V
```

**Comment by easye** [comment]
Behavior merged with manual test of RabbitMQ synthetic consumer with <https://github.com/armedbear/abcl/commit/23f045065673e4bfd7c59a30f1a99dd6b62606ee>
