### ISSUE TITLE
Top level form with lambda in function position won't compile

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#541]
To reproduce create a file with the form 
```
((lambda(x) (+ x 1)) 1)
```
Compile the file and one gets the error
```
The value (lambda (x) (+ x 1)) is not of type symbol.
```

If one wraps the form in a defun and calls that function then the file compiles. Similarly if it is just wrapped with (let () ...).

**Comment by alejandrozf** [comment]
I've tracked down the bug, it is introduced in release 0.27.0
