### ISSUE TITLE
Documentation: "inability to inspect local variables in a given call frame"

### ISSUE THREAD

**Issue by fosskers** [armedbear/abcl#619]
I was reading through the manual and noticed this point in Section 1.1.2, _Contemporary Common Lisp_:

> An incomplete implementation of interactive debugging mechanisms, namely a no-op version
of STEP6, the inability to inspect local variables in a given call frame, and the inability to
resume a halted computation at an arbitrarily selected call frame

In particular it states `the inability to inspect local variables in a given call frame`, and yet I am able to inspect local bindings in all the available stack frames while in the interactive debugger. Am I misunderstanding the original wording?

Cheers!

**Comment by fosskers** [comment]
Now that I'm testing it in SBCL, I'm actually seeing the same thing; I can't manage to get access to `b` within the debugger. 

However, the good news is that [Sly Stickers](http://joaotavora.github.io/sly/#Stickers) do work, so if I really need access to an inner variable, I can use those.

I think the original issue can be closed. Thanks!

**Comment by alanruttenberg** [comment]
@fosskers Have you tried to look at frames of functions that are interpreted? With ABCL-introspect those should be visible.

**Comment by fosskers** [comment]
It was the same result for either interpreted or compiled functions, although I was just using what Sly provides by default. I didn't try out `abcl-introspect`.

**Comment by alanruttenberg** [comment]
Right, it won't work unless abcl-introspect is loaded. Also, I'm not familiar with sly. Slime has the debugger support for this.
