### ISSUE TITLE
Printing line number/context when catching errors

### ISSUE THREAD

**Issue by helloimhana123** [armedbear/abcl#682]
Hello I've been trying to figure this out with no success. So my situation is this: I want to avoid the debugger because I want to print the error to a window, and keep the program running. So I've been using `handler-case` something like so:

```
(handler-case
  (load "ui.lsp")
  (error (c) (format t "Error: ~A~%" c))))
```

This works fine except the error isn't very informative. For example a missed parens will just print `Error: #<END-OF-FILE {794CB26B}>`. No indication of file, line number, or any sort of context. Is it possible to print those things?

**Comment by alejandrozf** [comment]
You can use _(sys:backtrace)_ to get the context of the error

**Comment by helloimhana123** [comment]
> You can use _(sys:backtrace)_ to get the context of the error

Sounds great. How do I make it into a string? Tried plopping it into format with `~A` or `~S` but it just says like `(#<LISP-STACK-FRAME (BACKTRACE) {DD20EBC}>)`.

**Comment by alejandrozf** [comment]
Yes, it is a list of internal stack-frames. 
 You can do this, for example:
 `(loop for bt in (sys:backtrace)
               do (print (jcall "toLispString" bt)))`

**Comment by helloimhana123** [comment]
> Yes, it is a list of internal stack-frames. You can do this, for example: `(loop for bt in (sys:backtrace) do (print (jcall "toLispString" bt)))`

That doesn't do anything. It just seems to print two newlines.

**Comment by alejandrozf** [comment]
I suppose it depends on the code being executed 
In the plain REPL I have:
```
CL-USER(1): (loop for bt in (sys:backtrace) do (print (jcall "toLispString" bt)))

"(SYSTEM:BACKTRACE)" 
"(SYSTEM::%EVAL (LOOP FOR BT IN (SYSTEM:BACKTRACE) DO (PRINT (JCALL \"toLispString\" BT))))" 
"(EVAL (LOOP FOR BT IN (SYSTEM:BACKTRACE) DO (PRINT (JCALL \"toLispString\" BT))))" 
"(SYSTEM:INTERACTIVE-EVAL (LOOP FOR BT IN (SYSTEM:BACKTRACE) DO (PRINT (JCALL \"toLispString\" BT))))" 
"(TOP-LEVEL::REPL)" 
"(TOP-LEVEL::TOP-LEVEL-LOOP)" 
NIL
CL-USER(2): 
```

**Comment by helloimhana123** [comment]
> I suppose it depends on the code being executed In the plain REPL I have:

It seems like `sys:backtrace` generates a trace from where it was called. For example I made this test file:

```
(defun a2 () (/ 1 0))

(defun a ()
  (let ((b 3)) (progn (+ b 4) (a2))))

(defun c ()
  (handler-case (a) (condition (c) (loop for bt in (sys:backtrace) do (print (jcall "toLispString" bt))))))

(c)
```

This gives me the output:

```
"(SYSTEM:BACKTRACE)"
"(C)"
```

If I instead move the loop to where the error happened, I get the kind of output I want. But of course I don't want to do that, I want to catch the error somewhere higher up the chain, and get a stack trace from where the error happened. How can I do that?

**Comment by helloimhana123** [comment]
Oke nvm I figured out I can use `handler-bind` instead which will give the correct output. Nice. 

Now next question. How do I get filename and line number of the error?

I tried to use `*LOAD-TRUENAME*` which worked when loading a single file from a jar, but just gave `Nil` when used in my project.
