### ISSUE TITLE
bug in destructuring-bind <http://abcl.org/trac/ticket/417>

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#8]
```
(defun test (args) (destructuring-bind (a b &rest c) args (list a b)))
(test '(1))
-> '(1 nil)
```
should signal an error 

without the &rest args 
```
(defun test (args) (destructuring-bind (a b) args (list a b)))
(test '(1)) 
```
signals an error as expected

**Comment by Ferada** [comment]
I'm relatively sure I have a fix for this here https://github.com/Ferada/abcl/commit/2422740c094d5bbb757df82d730b76d36e8f42f1.
