### ISSUE TITLE
READER-ERROR - FORMAT-CONTROL is preformatted

### ISSUE THREAD

**Issue by phoe** [armedbear/abcl#85]
ABCL 1.5.0

```common-lisp
CL-USER> (handler-case (read-from-string "cl:asdfsad") (error (e) (describe e)))

#<READER-ERROR {B20D3DF}> is an instance of #<STANDARD-CLASS READER-ERROR {B0459D1}>.
The following slots have :INSTANCE allocation:
  FORMAT-CONTROL     "The symbol \"ASDFSAD\" was not found in package CL."
  FORMAT-ARGUMENTS   NIL
  STREAM             #S(SYSTEM::STRING-INPUT-STREAM)
```
The `FORMAT-CONTROL` string is preformatted, and it should not be.

`FORMAT-CONTROL` should be `"The symbol ~S was not found in package CL."` and `FORMAT-ARGUMENTS` should be `("ASDFSAD" CL)`.

**Comment by PuercoPop** [comment]
Digging a little bit the error is in [Stream.java](https://github.com/armedbear/abcl/blob/master/src/org/armedbear/lisp/Stream.java#L1194-L1202). If the symbol was not external to a package you should get a similar error.

However the class [ReaderError](https://github.com/armedbear/abcl/blob/master/src/org/armedbear/lisp/ReaderError.java) doesn't appear to have a constructor that allows one to pass format arguments. Should we just create another constructor that takes 'rest' arguments as the last argument? Or would it be prefereable to create a different constructor for the one argument case only?

**Comment by phoe** [comment]
I don't think I'm the proper person to answer your questions. I'm not competent in ABCL internals.

**Comment by easye** [comment]
Merged in <https://github.com/armedbear/abcl/commit/2e80b56d7384dd42e03d580cdd79872c9af13d32>

There is no consistency in adding constructors for the Java-side implementations of things.  We essentially just add constructors as needed.
