### ISSUE TITLE
ABCL Trac issue tracker not working.

### ISSUE THREAD

**Issue by defunkydrummer** [armedbear/abcl#91]
TRAC issue tracker at:

https://abcl.org/trac/

gives:

Trac Error

TracError: No Trac environment found at /srv/project/armedbear/trac
[Errno 2] No such file or directory: '/srv/project/armedbear/trac/VERSION'

**Comment by defunkydrummer** [comment]
Trac is working now, so i'll close this issue myself.

**Comment by easye** [comment]
@defunkydrummer Thanks for the service outage report.  

For more visibility to the parties responsible for hosting the ABCL infrastructure, namely [common.lisp.net](https://common-lisp.net/), such outages will be more rapidly handled by either shooting a message on Freenode IRC to #common-lisp.net or to the  [clo-devel@](https://mailman.common-lisp.net/listinfo/clo-devel> mailing list.
